version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "${DB_PORT}:${DB_PORT}"